### ISSUE TITLE
Questions about the cra-template-ethereum-fullstack template for create react app CLI

### ISSUE THREAD

**Issue by luisnaranjo733** [ethereum-bootcamp/ethereum-fullstack-template#6]
I noticed that this repo is based on the [cra-template-ethereum-fullstack](https://www.npmjs.com/package/cra-template-ethereum-fullstack) template according to how the [--template flag](https://create-react-app.dev/docs/getting-started#selecting-a-template) of the create-react-app CLI works. 

Is this template used commonly in dapp development? For production apps, do they typically start from a template like this one or plug in all the pieces manually?

**Comment by shubham-kanodia** [comment]
In production apps, you would ideally have different repositories for frontend and solidity contracts. This is more for quick development purposes. You can check [Uniswap V3 Staker](https://github.com/Uniswap/v3-staker) to see how a production contracts repo would look like
